theme: jekyll-theme-cayman
title: 2019年度 山口大 enPiT2 アジャイル開発手法
description: 自己紹介

初めまして！
###こんにちは  
OuchiTakeruです！
  
##出身  
>NGANO 

<details>
<summary>好きな食べ門</summary>
1. 肉<br>
2. メロン<br>
3. 寿司<br>
4.カレー   
</details>
